# Generated by Django 4.1.9 on 2023-10-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_mymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("publication_date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="mymodel",
            name="name",
        ),
        migrations.AddField(
            model_name="mymodel",
            name="field1",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mymodel",
            name="field2",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
